from .utils import Command
from .functions import *
from ._bonds import bonds_card

commands = [
    Command(operations, ("图片操作", "改图", "图片"), r"(?:图片操作|改图|图片)(?P<opt>.+)", arg_type="Arg"),
    Command(universal, ("万能表情", "空白表情"), arg_type="Args"),
    Command(petpet, ("摸", "摸摸", "摸头", "rua"), r"摸摸?头?|rua", arg_type="Arg"),
    Command(kiss, ("亲", "亲亲"), r"亲亲?"),
    Command(rub, ("贴", "贴贴", "蹭", "蹭蹭"), r"贴贴?|蹭蹭?"),
    Command(capoo_rub, ("咖波蹭",)),
    Command(play, ("顶", "玩")),
    Command(pat, ("拍",)),
    Command(rip, ("撕",)),
    Command(rip_angrily, ("怒撕",)),
    Command(throw, ("丢", "扔")),
    Command(throw_gif, ("抛", "掷")),
    Command(crawl, ("爬",), arg_type="Arg"),
    Command(support, ("精神支柱",)),
    Command(always, ("一直",)),
    Command(loading, ("加载中",)),
    Command(turn, ("转",)),
    Command(littleangel, ("小天使",), arg_type="Arg"),
    Command(dont_touch, ("不要靠近",)),
    Command(alike, ("一样",)),
    Command(roll, ("滚",)),
    Command(play_game, ("玩游戏",), r"来?玩游戏", arg_type="Arg"),
    Command(worship, ("膜", "膜拜"), r"膜拜?"),
    Command(eat, ("吃",)),
    Command(klee_eat, ("可莉吃",)),
    Command(bite, ("啃",)),
    Command(hutao_bite, ("胡桃啃",)),
    Command(police, ("警察",)),
    Command(zhengjian, ("出警", "出示证件", "证件")),
    Command(ask, ("问问",), r"去?问问", arg_type="Arg"),
    # Command(prpr, ("舔", "舔屏", "prpr"), r"舔屏?|prpr"),
    Command(twist, ("搓",)),
    Command(wallpaper, ("墙纸",)),
    Command(china_flag, ("国旗",)),
    Command(make_friend, ("交个朋友",), arg_type="Arg"),
    Command(back_to_work, ("继续干活", "打工人")),
    Command(perfect, ("完美",), r"完美的?"),
    Command(follow, ("关注",), arg_type="Arg"),
    Command(my_friend, ("我朋友[name]说",), r"我(?:有个)?朋友(?P<name>.*?)说", arg_type="Args"),
    Command(paint, ("这像画吗",)),
    Command(shock, ("震惊",)),
    Command(coupon, ("兑换券",), arg_type="Arg"),
    Command(listen_music, ("听音乐",)),
    Command(dianzhongdian, ("典中典", "黑白草图"), arg_type="Arg"),
    Command(funny_mirror, ("哈哈镜",)),
    Command(love_you, ("永远爱你",)),
    Command(symmetric, ("对称",), arg_type="Arg"),
    Command(safe_sense, ("安全感",), arg_type="Arg"),
    Command(always_like, ("我永远喜欢",), r"我?永远喜欢", arg_type="Args"),
    Command(interview, ("采访",), arg_type="Arg"),
    Command(punch, ("打拳",)),
    Command(cyan, ("群青",)),
    Command(pound, ("捣",)),
    Command(thump, ("捶",)),
    Command(need, ("需要", "你可能需要")),
    Command(cover_face, ("捂脸",)),
    Command(knock, ("敲",)),
    Command(garbage, ("垃圾", "垃圾桶"), r"垃圾桶?"),
    Command(whyatme, ("为什么@我",), r"为什么(?:@|at)我"),
    Command(decent_kiss, ("像样的亲亲",)),
    Command(jiujiu, ("啾啾",)),
    Command(suck, ("吸", "嗦")),
    Command(hammer, ("锤",)),
    Command(tightly, ("紧贴", "紧紧贴着")),
    Command(distracted, ("注意力涣散",)),
    Command(anyasuki, ("阿尼亚喜欢",), arg_type="Arg"),
    Command(thinkwhat, ("想什么",)),
    Command(keepaway, ("远离",), arg_type="Arg"),
    Command(marriage, ("结婚申请", "结婚登记")),
    Command(painter, ("小画家",)),
    Command(repeat, ("复读",)),
    Command(anti_kidnap, ("防诱拐",)),
    Command(charpic, ("字符画",)),
    Command(mywife, ("这是我的老婆",), r"这是(?P<ta>\S+)的(?P<name>\S+)"),
    Command(walnutpad, ("胡桃平板",)),
    Command(walnutzoom, ("胡桃放大",)),
    Command(teach, ("讲课", "敲黑板")),
    Command(addiction, ("上瘾", "毒瘾发作")),
    Command(gun, ("手枪",)),
    Command(blood_pressure, ("高血压",)),
    Command(read_book, ("看书",)),
    Command(call_110, ("遇到困难请拨打",)),
    Command(confuse, ("迷惑",)),
    Command(hit_screen, ("打穿", "打穿屏幕"), r"打穿(?:屏幕)?"),
    Command(fencing, ("击剑", "🤺")),
    Command(hug_leg, ("抱大腿",)),
    Command(tankuku_holdsign, ("唐可可举牌",)),
    Command(no_response, ("无响应",)),
    Command(hold_tight, ("抱紧",)),
    Command(look_flat, ("看扁",), arg_type="Args"),
    Command(look_this_icon, ("看图标",), arg_type="Arg"),
    Command(captain, ("舰长",)),
    Command(jiji_king, ("急急国王",), arg_type="Args"),
    Command(incivilization, ("不文明",), arg_type="Arg"),
    Command(together, ("一起",), arg_type="Arg"),
    Command(wave, ("波纹",)),
    Command(rise_dead, ("诈尸", "秽土转生")),
    Command(kirby_hammer, ("卡比锤", "卡比重锤")),
    Command(wooden_fish, ("木鱼",)),
    Command(karyl_point, ("凯露指",), arg_type="Arg"),
    Command(kick_ball, ("踢球",)),
    Command(smash, ("砸",)),
    Command(bocchi_draft, ("波奇手稿",)),
    Command(sit_still, ("坐得住", "坐的住"), arg_type="Arg"),
    Command(learn, ("偷学",), arg_type="Arg"),
    Command(trance, ("恍惚",)),
    Command(dinosaur, ("恐龙", "小恐龙")),
    Command(scratch_head, ("挠头",)),
    Command(applaud, ("鼓掌",)),
    Command(chase_train, ("追列车", "追火车")),
    Command(kaleidoscope, ("万花筒", "万花镜"), arg_type="Arg"),
    Command(overtime, ("加班",)),
    Command(avatar_formula, ("头像公式", "等价无穷小")),
    Command(potato, ("土豆",)),
    Command(printing, ("打印",)),
    Command(name_generator, ("亚文化取名机", "亚名")),
    Command(beat_head, ("拍头", "怎么说话的"), arg_type="Arg"),
    Command(bubble_tea, ("奶茶",)),
    Command(bonds_card, ("羁绊牌",), arg_type="Args"),
]
